### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    selection = self.selection;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "a1d6873040c637398b61ca7a5f229d62429f959f";
          sha256 = "19acm60m43si703psjzkl0q1zxsmgwj4kayqinzgjvrrq0vdmxmh";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.14.0";
  selection = 
  {
    alcotest = 
    {
      pname = "alcotest";
      version = "1.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/alcotest/releases/download/1.6.0/alcotest-1.6.0.tbz";
        sha256 = "0a939glmndarbnr3w4ilvnkjzh7g2inmdvypn7rlz1wmhdkgj07x";
      };
      opamInputs = 
      {
        inherit (selection) uutf stdlib-shims re ocaml-syntax-shims ocaml fmt
        dune cmdliner astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/alcotest/alcotest.1.6.0";
        hash = "sha256:0hvmdg6kp6zcnjwa3gc85ilfm67iinrdjpjjc5ginhc43hbd93ap";
      };
    };
    astring = 
    {
      pname = "astring";
      version = "0.8.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/astring/releases/astring-0.8.5.tbz";
        sha256 = "1ykhg9gd3iy7zsgyiy2p9b1wkpqg9irw5pvcqs3sphq71iir4ml6";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/astring/astring.0.8.5";
        hash = "sha256:1djnad9sq12idlakj069xvwm2nn7wqm137pqbxxai5frkgi08x74";
      };
    };
    base = 
    {
      pname = "base";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/base-v0.15.0.tar.gz";
        sha256 = "0gd5lq9474hbgzczb07pazqrbnnjjyfw8i9225bq95594i1swmw6";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base/base.v0.15.0";
        hash = "sha256:12f5im78rqg349nsxhvy2skyyf223nf3nmrq8pni08psf5l45cz3";
      };
    };
    base-bigarray = 
    {
      pname = "base-bigarray";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bigarray/base-bigarray.base";
        hash = "sha256:1hgfwxh4vdv21m2a4g506y27pcv912v67qi4svrn53rgc43ckv6b";
      };
    };
    base-bytes = 
    {
      pname = "base-bytes";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bytes/base-bytes.base";
        hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
      };
    };
    base-threads = 
    {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-threads/base-threads.base";
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
      };
    };
    base-unix = 
    {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-unix/base-unix.base";
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
      };
    };
    bigarray-compat = 
    {
      pname = "bigarray-compat";
      version = "1.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/bigarray-compat/releases/download/v1.1.0/bigarray-compat-1.1.0.tbz";
        sha256 = "1m8q6ywik6h0wrdgv8ah2s617y37n1gdj4qvc86yi12winj6ji23";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bigarray-compat/bigarray-compat.1.1.0";
        hash = "sha256:1hq7lmh99p720plkbv1faqqz2xz4ff9g49kkpsryg9ws3ld8ry05";
      };
    };
    camlp-streams = 
    {
      pname = "camlp-streams";
      version = "5.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/camlp-streams/archive/v5.0.1.tar.gz";
        sha256 = "196rn0z2q53f8is5bwln1n5qzipn5bg3wnflnmzlxfz90qjgcwdd";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/camlp-streams/camlp-streams.5.0.1";
        hash = "sha256:177a68cgm23pryyji88dvn300qz55sl154wfwmzvp8arhs7yg6bn";
      };
    };
    cmdliner = 
    {
      pname = "cmdliner";
      version = "1.1.1";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/cmdliner/releases/cmdliner-1.1.1.tbz";
        sha256 = "1yxm4x34cbi06bfld601ds9drlbnyx0797ym3n6yyh4rlz1qgbm1";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cmdliner/cmdliner.1.1.1";
        hash = "sha256:0zp0q9213an1spx8ps70xlm9rhmjfqmixh59b3mb7dsj1r6p19i7";
      };
    };
    conf-libffi = 
    {
      pname = "conf-libffi";
      version = "2.0.0";
      src = null;
      opamInputs = {
                     inherit (selection) conf-pkg-config;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-libffi/conf-libffi.2.0.0";
        hash = "sha256:09yxvlij8k2mrbwm1lphjqdrlk9r68jwzng6gfp94qqhsnpndj7n";
      };
      buildInputs = [ (pkgs.libffi) ];
    };
    conf-pkg-config = 
    {
      pname = "conf-pkg-config";
      version = "2";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-pkg-config/conf-pkg-config.2";
        hash = "sha256:1rli6809glz5g9xwp4wsjidc39za4n58xcpkamy6fymfnqha225n";
      };
      buildInputs = [ (pkgs.pkgconfig) ];
    };
    conf-protoc = 
    {
      pname = "conf-protoc";
      version = "1.0.0";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-protoc/conf-protoc.1.0.0";
        hash = "sha256:0f0hg06yj02jipa0qm4j9nwkimk7k88clsc9flvy9r30yp46wgmz";
      };
      buildInputs = [ (pkgs.libprotobuf-dev or null)
                       (pkgs.libprotobuf-devel or null)
                       (pkgs.protobuf or null)
                       (pkgs.protobuf-compiler or null)
                       (pkgs.protobuf-dev or null)
                       (pkgs.protobuf-devel or null) ];
    };
    cppo = 
    {
      pname = "cppo";
      version = "1.6.9";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/cppo/archive/v1.6.9.tar.gz";
        sha256 = "0sm2vn5y7w7fyrwkv7f86y4nvs5vsrqy1x2nidy0lcqxq62ns0qn";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cppo/cppo.1.6.9";
        hash = "sha256:19i6yqv9lq09v3xw1sfqayh40sihhd4hfyvk9dwz1m5dv1g63xlp";
      };
    };
    csexp = 
    {
      pname = "csexp";
      version = "1.5.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.1/csexp-1.5.1.tbz";
        sha256 = "00mc19f89pxpmjl62862ya5kjcfrl8rjzvs00j05h2m9bw3f81fn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/csexp/csexp.1.5.1";
        hash = "sha256:01lc95kz13gpki4xazyh6n20kv1g9inyb5myv240wl2n9v50z8fl";
      };
    };
    ctypes = 
    {
      pname = "ctypes";
      version = "0.20.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocamllabs/ocaml-ctypes/archive/0.20.1.tar.gz";
        sha256 = "1iwf4yv29zp7sg78qw7jcsiyyk1xbjvjxrsjliay98jjq75imgvq";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocaml integers
        bigarray-compat;
        mirage-xen = selection.mirage-xen or null;
        ctypes-foreign = selection.ctypes-foreign or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ctypes/ctypes.0.20.1";
        hash = "sha256:1sziacwyjlhn5z1qylihyla76v7lifwi6bwdwlfiwbcdykssdi7g";
      };
    };
    ctypes-foreign = 
    {
      pname = "ctypes-foreign";
      version = "0.18.0";
      src = null;
      opamInputs = 
      {
        inherit (selection) conf-pkg-config conf-libffi;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ctypes-foreign/ctypes-foreign.0.18.0";
        hash = "sha256:0mr8z6hjdd8073zya2w0v5m5yv8scq90vw2d1paanib66m4y5sgm";
      };
    };
    dune = 
    {
      pname = "dune";
      version = "3.1.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.1.1/fiber-3.1.1.tbz";
        sha256 = "0q3bbarnkxglypw2w4rccs9fn093dgn0jdc7qx08i68vmda48j02";
      };
      opamInputs = 
      {
        inherit (selection) base-unix
        base-threads;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune/dune.3.1.1";
        hash = "sha256:1x9abf6ba2yw16ng2l3zra1qb2sq2vxpvcbkc02fm9i0i6irz9qb";
      };
    };
    dune-build-info = 
    {
      pname = "dune-build-info";
      version = "3.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.2.0/chrome-trace-3.2.0.tbz";
        sha256 = "1g6m3a5b1nhvrxw5agzmng7ayy1rwbib56x8dyr1xvbrmvkbq7xx";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-build-info/dune-build-info.3.2.0";
        hash = "sha256:14m1yvk5syqjr48jsj8696gk802zzbq7alkgmqf0frjpyscaw6h1";
      };
    };
    dune-configurator = 
    {
      pname = "dune-configurator";
      version = "3.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.2.0/chrome-trace-3.2.0.tbz";
        sha256 = "1g6m3a5b1nhvrxw5agzmng7ayy1rwbib56x8dyr1xvbrmvkbq7xx";
      };
      opamInputs = {
                     inherit (selection) ocaml dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-configurator/dune-configurator.3.2.0";
        hash = "sha256:0658amxrfkxa7h7sx13lks7k2kpcq39mavx2jy8hnyg047jzn848";
      };
    };
    dune-rpc = 
    {
      pname = "dune-rpc";
      version = "3.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.2.0/chrome-trace-3.2.0.tbz";
        sha256 = "1g6m3a5b1nhvrxw5agzmng7ayy1rwbib56x8dyr1xvbrmvkbq7xx";
      };
      opamInputs = 
      {
        inherit (selection) xdg stdune pp ordering dyn dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-rpc/dune-rpc.3.2.0";
        hash = "sha256:1s87v583h3jdknf52wd0vgazv0pbq35f8nsc4ngy1wfw4kanqsvc";
      };
    };
    dyn = 
    {
      pname = "dyn";
      version = "3.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.2.0/chrome-trace-3.2.0.tbz";
        sha256 = "1g6m3a5b1nhvrxw5agzmng7ayy1rwbib56x8dyr1xvbrmvkbq7xx";
      };
      opamInputs = 
      {
        inherit (selection) pp ordering ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dyn/dyn.3.2.0";
        hash = "sha256:0m39b0vwbp08dy264sjips0psskga0nab2pbl519clbina830wz6";
      };
    };
    fiber = 
    {
      pname = "fiber";
      version = "3.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.2.0/chrome-trace-3.2.0.tbz";
        sha256 = "1g6m3a5b1nhvrxw5agzmng7ayy1rwbib56x8dyr1xvbrmvkbq7xx";
      };
      opamInputs = 
      {
        inherit (selection) stdune ocaml dyn dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fiber/fiber.3.2.0";
        hash = "sha256:1qvb2awh1qlfcwwjdg73jbm5adhzpqdwbq8ipjmy7mybyl8whw79";
      };
    };
    fmt = 
    {
      pname = "fmt";
      version = "0.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fmt/releases/fmt-0.9.0.tbz";
        sha256 = "0q8j2in2473xh7k4hfgnppv9qy77f2ih89yp6yhpbp92ba021yzi";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
        base-unix = selection.base-unix or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fmt/fmt.0.9.0";
        hash = "sha256:1czh5i3i4mkf9xfasji3v7n821qmnnandlklh67ali0x87brldny";
      };
    };
    fpath = 
    {
      pname = "fpath";
      version = "0.7.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fpath/releases/fpath-0.7.3.tbz";
        sha256 = "03z7mj0sqdz465rc4drj1gr88l9q3nfs374yssvdjdyhjbqqzc0j";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fpath/fpath.0.7.3";
        hash = "sha256:1pnskgw9fqq4kg1x4sc4vcv9rh0kksilx4qngwafpyss42mqq2i2";
      };
    };
    grpc = 
    {
      pname = "grpc";
      version = "0.0.1";
      src = self.directSrc "grpc";
      opamInputs = 
      {
        inherit (selection) ppx_deriving ocaml-protoc-plugin ocaml lwt_ppx
        lwt logs hmap dune ctypes-foreign ctypes;
      };
      opamSrc = "grpc.opam";
      buildInputs = [ (pkgs.grpc or null) (pkgs.libgrpc-dev or null) ];
    };
    hmap = 
    {
      pname = "hmap";
      version = "0.8.1";
      src = pkgs.fetchurl 
      {
        url = "http://erratique.ch/software/hmap/releases/hmap-0.8.1.tbz";
        sha256 = "10xyjy4ab87z7jnghy0wnla9wrmazgyhdwhr4hdmxxdn28dxn03a";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/hmap/hmap.0.8.1";
        hash = "sha256:19yc0fm5c0wzxyrwfy3bcb6yh3hbgwrhhh94ggzjs7di8vv9bkv1";
      };
    };
    integers = 
    {
      pname = "integers";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocamllabs/ocaml-integers/archive/0.7.0.tar.gz";
        sha256 = "11f67v9bijhkbnia7vrdp6sfpyw92kp39kn4p1p2860qkbx1gdcb";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/integers/integers.0.7.0";
        hash = "sha256:02dayvzqz5bz6hc0x8wxmm5w5ad2j7xbwf32a1qgh0fkm0y4inic";
      };
    };
    jane-street-headers = 
    {
      pname = "jane-street-headers";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/jane-street-headers-v0.15.0.tar.gz";
        sha256 = "1r27r0bxxa0iaah5rm84lwhrmh784vfpmb6056hpv0p34rxs7r1l";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jane-street-headers/jane-street-headers.v0.15.0";
        hash = "sha256:134qp5ww1ws8k9i43sr13ivibsz88si142cdkllrcw9ib9d4aa5g";
      };
    };
    jst-config = 
    {
      pname = "jst-config";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/jst-config/archive/refs/tags/v0.15.1.tar.gz";
        sha256 = "06xlyg0cyvv742haypdjbl82b5h5mla9hhcg3q67csq1nfxyalvh";
      };
      opamInputs = 
      {
        inherit (selection) ppx_assert ocaml dune-configurator dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jst-config/jst-config.v0.15.1";
        hash = "sha256:03px4smpvwvqcvdn38jyjcfb2q41qpcgcyi8pj9ig7a76hzm5hrv";
      };
    };
    lambda-term = 
    {
      pname = "lambda-term";
      version = "3.3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/lambda-term/releases/download/3.3.1/lambda-term-3.3.1.tbz";
        sha256 = "0g6vjl9qlggiskx2n78vhjgcha4h9vxmbyxighayjsnmjvhcnxsv";
      };
      opamInputs = 
      {
        inherit (selection) zed react ocaml mew_vi lwt_react lwt logs dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lambda-term/lambda-term.3.3.1";
        hash = "sha256:0rdszhn7gwqdbfrdx48yh8iw7gvm4dym2a7xh3kfih1gd5bagkys";
      };
    };
    logs = 
    {
      pname = "logs";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/logs/releases/logs-0.7.0.tbz";
        sha256 = "1jnmd675wmsmdwyb5mx5b0ac66g4c6gpv5s4mrx2j6pb0wla1x46";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        lwt = selection.lwt or null;
        js_of_ocaml = selection.js_of_ocaml or null;
        fmt = selection.fmt or null;
        cmdliner = selection.cmdliner or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/logs/logs.0.7.0";
        hash = "sha256:0pys6d25bghrwvwd4gflib2yyp5fvdy0rkivbdyli5dmp5j35a3n";
      };
    };
    lwt = 
    {
      pname = "lwt";
      version = "5.6.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/5.6.1.tar.gz";
        sha256 = "1837iagnba58018ag82c9lwaby01c031547n08jjyj8q5q6lfjgb";
      };
      opamInputs = 
      {
        inherit (selection) ocplib-endian ocaml dune-configurator dune
        cppo;
        conf-libev = selection.conf-libev or null;
        base-unix = selection.base-unix or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt/lwt.5.6.1";
        hash = "sha256:0y6rif2d9ggd7mwv4hipawn8jjfn4vdk57i6zld2izqpj6f6m9kc";
      };
    };
    lwt_ppx = 
    {
      pname = "lwt_ppx";
      version = "2.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/5.6.0.tar.gz";
        sha256 = "1qg5wjlmrnd295lljncr1db1rw50pr13wmak3rcg92n9wd1fzm0v";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml lwt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_ppx/lwt_ppx.2.1.0";
        hash = "sha256:09kc2bwmqq41983xivild7az3s62nrhp62iinvc2b6lpcldzvqqc";
      };
    };
    lwt_react = 
    {
      pname = "lwt_react";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/5.6.0.tar.gz";
        sha256 = "1qg5wjlmrnd295lljncr1db1rw50pr13wmak3rcg92n9wd1fzm0v";
      };
      opamInputs = 
      {
        inherit (selection) react ocaml lwt dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_react/lwt_react.1.2.0";
        hash = "sha256:0nar357nms1b90rr0iy2pa0m982yibwkbnx71hsz2v16kj9n831g";
      };
    };
    mew = 
    {
      pname = "mew";
      version = "0.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/mew/archive/0.1.0.tar.gz";
        sha256 = "1rjri9mgfb9gn9fmjn0ax21y9jd9wkvr7mmx2jrlqmzgabmqrlv4";
      };
      opamInputs = 
      {
        inherit (selection) trie result ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mew/mew.0.1.0";
        hash = "sha256:0g9xms016f909fzbwgxcy0k4xmvr5zk5bhnz66v9vpsiak2qm4s3";
      };
    };
    mew_vi = 
    {
      pname = "mew_vi";
      version = "0.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/mew_vi/archive/0.5.0.tar.gz";
        sha256 = "1nmg3cysglgw4115n5zpz4azrfbnfxkn2kvw73chzs69viygm4m6";
      };
      opamInputs = 
      {
        inherit (selection) react ocaml mew dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mew_vi/mew_vi.0.5.0";
        hash = "sha256:0zsfhxpff78cqk2c81parajb59m7hqf6v8arksxbyfha6mls65hz";
      };
    };
    ocaml = 
    {
      pname = "ocaml";
      version = "4.14.0";
      src = null;
      opamInputs = 
      {
        inherit (selection)
        ocaml-config;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml/ocaml.4.14.0";
        hash = "sha256:1p4i6fpw1psp5izwcdswcilkkzicdm33mwzg5hhm2cqn85784hmq";
      };
    };
    ocaml-base-compiler = 
    {
      pname = "ocaml-base-compiler";
      version = "4.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml/archive/4.14.0.tar.gz";
        sha256 = "1s2ml56m8i43jgvr59vx09javdrwfps8p7az9h2x2a1g71h45x1r";
      };
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.14.0";
        hash = "sha256:1scnnh353kx76icrawbykf537fmfddlgvddwnmi6pnka3hjkzgix";
      };
    };
    ocaml-compiler-libs = 
    {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
        sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
        hash = "sha256:1blynia10j8vyj559kcvc7ic69zq6qjjn092fcsjzfw6czd8ya2c";
      };
    };
    ocaml-config = 
    {
      pname = "ocaml-config";
      version = "2";
      src = null;
      opamInputs = 
      {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-config/ocaml-config.2";
        hash = "sha256:0h0hgqq9mbywvqygppfdc50gf9ss8a97l4dgsv3hszmzh6gglgrg";
      };
    };
    ocaml-lsp-server = 
    {
      pname = "ocaml-lsp-server";
      version = "1.12.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-lsp/releases/download/1.12.2/lsp-1.12.2.tbz";
        sha256 = "0ffxjwslgn1kwwb9211wc9cbw0arx4bn9k75ll9sk2l4gicch9fg";
      };
      opamInputs = 
      {
        inherit (selection) yojson xdg uutf stdune spawn re
        ppx_yojson_conv_lib pp ordering omd octavius ocamlformat-rpc-lib
        ocaml fiber dyn dune-rpc dune-build-info dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-lsp-server/ocaml-lsp-server.1.12.2";
        hash = "sha256:03k0sz8slfb8qfc5q2zvhjvp1scnpbqrnxafdmvwhalkdfy2lcv8";
      };
    };
    ocaml-protoc-plugin = 
    {
      pname = "ocaml-protoc-plugin";
      version = "development";
      src = self.directSrc "ocaml-protoc-plugin";
      opamInputs = 
      {
        inherit (selection) ocaml dune conf-protoc conf-pkg-config;
      };
      opamSrc = "ocaml-protoc-plugin.opam";
    };
    ocaml-syntax-shims = 
    {
      pname = "ocaml-syntax-shims";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ocaml-syntax-shims/releases/download/1.0.0/ocaml-syntax-shims-1.0.0.tbz";
        sha256 = "1j7848khli4p7j8i2kmnvhdnhcwhy3zgdpf5ds5ic30ax69y3cl9";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-syntax-shims/ocaml-syntax-shims.1.0.0";
        hash = "sha256:0qnm1db0298yqcn6j9fmb0l4gr5nhcar8plskj39917invyamgd2";
      };
    };
    ocamlbuild = 
    {
      pname = "ocamlbuild";
      version = "0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.14.1.tar.gz";
        sha256 = "0ml2y3dqhhbwlf94l3jgz6gfhhfp41qaf1sjm8p8c37q1vzpj4jf";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlbuild/ocamlbuild.0.14.1";
        hash = "sha256:04ws6wbbsv56r4b6f29514inn77d91gb6sa8z62bxkswk1s1r1fn";
      };
    };
    ocamlfind = 
    {
      pname = "ocamlfind";
      version = "1.9.5";
      src = pkgs.fetchurl 
      {
        url = "http://download.camlcity.org/download/findlib-1.9.5.tar.gz";
        sha256 = "0w9578j1561f5gi51sn2jgxm3kh3sn88cpannhdkqcdg1kk08iqd";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlfind/ocamlfind.1.9.5";
        hash = "sha256:1z0f7dvfsnx56ign40s3hrpz16pmhfka740y730m13lk8bw92iv1";
      };
    };
    ocamlformat-rpc-lib = 
    {
      pname = "ocamlformat-rpc-lib";
      version = "0.24.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ocamlformat/releases/download/0.24.1/ocamlformat-0.24.1.tbz";
        sha256 = "1kj1ykax4150i1z801bxjnllkhb6lyj728vvad8fm04gh7ljad02";
      };
      opamInputs = {
                     inherit (selection) ocaml dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlformat-rpc-lib/ocamlformat-rpc-lib.0.24.1";
        hash = "sha256:1bcbk85vm0b30xhh6fjv3ikzs737fjjs9hkyaqcgk835yd2rr5kw";
      };
    };
    ocplib-endian = 
    {
      pname = "ocplib-endian";
      version = "1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/OCamlPro/ocplib-endian/archive/refs/tags/1.2.tar.gz";
        sha256 = "085kskr0cxcnv2d62n3jq1r273p7giisy56zfl26mm7amvl79blp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cppo base-bytes;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocplib-endian/ocplib-endian.1.2";
        hash = "sha256:1jldvb471gyhkrzwfvqg722l3a8dc37hhhyas66skjzfmqyi2pnh";
      };
    };
    octavius = 
    {
      pname = "octavius";
      version = "1.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-doc/octavius/archive/v1.2.2.tar.gz";
        sha256 = "1bg0fcm7haqxvx5wx2cci0mbbq0gf1vw9fa4kkd6jsriw1611jga";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/octavius/octavius.1.2.2";
        hash = "sha256:0bagilkanfjyi56hrk9dw43xs6zry9p8n3l55r3d58v5hz2xsbwl";
      };
    };
    odoc = 
    {
      pname = "odoc";
      version = "2.1.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/odoc/releases/download/2.1.1/odoc-2.1.1.tbz";
        sha256 = "1zc7z627hlzsawhy2kxv11j1yvfzbnwlnp2jjlmkmz6hik9dnx7m";
      };
      opamInputs = 
      {
        inherit (selection) tyxml result odoc-parser ocaml fpath fmt dune
        cppo cmdliner astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/odoc/odoc.2.1.1";
        hash = "sha256:0ccnp0jf29454z7vyjkwq2jwhazzz14jpm3w4bhbfjygkw3s107q";
      };
    };
    odoc-parser = 
    {
      pname = "odoc-parser";
      version = "1.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-doc/odoc-parser/releases/download/1.0.1/odoc-parser-1.0.1.tbz";
        sha256 = "0b3xj3xs5s1pb3vl82zmlddv181b3zj9c7mhpa0fjq0v43jfifx2";
      };
      opamInputs = 
      {
        inherit (selection) result ocaml dune camlp-streams astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/odoc-parser/odoc-parser.1.0.1";
        hash = "sha256:16mh4ar6ymclln8rm5xvnr2ljwqgp3hpw6n6zhzi5p7a1piag421";
      };
    };
    omd = 
    {
      pname = "omd";
      version = "1.3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/Chris00/omd/releases/download/1.3.1/omd-1.3.1.tar.gz";
        sha256 = "1sgdgzpx96br7npj8mh91cli5mqmzsjpngwm7x4212n3k1d0ivwa";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml base-bytes
        base-bigarray;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/omd/omd.1.3.1";
        hash = "sha256:09fzyagdfcj1b2bwj5hacbda9lldicd0a59sac5j5nls8x8rsgcc";
      };
    };
    ordering = 
    {
      pname = "ordering";
      version = "3.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.2.0/chrome-trace-3.2.0.tbz";
        sha256 = "1g6m3a5b1nhvrxw5agzmng7ayy1rwbib56x8dyr1xvbrmvkbq7xx";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ordering/ordering.3.2.0";
        hash = "sha256:1zaqxm6xfdr1g49a0q9xw604lhqdcw06sl2qvkc8my5hcz5m3xf5";
      };
    };
    pp = 
    {
      pname = "pp";
      version = "1.1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/pp/releases/download/1.1.2/pp-1.1.2.tbz";
        sha256 = "0mhxmzsraid4yw18zr6pyjfrhvf873ls8vfd1yapdfxijs6yk974";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/pp/pp.1.1.2";
        hash = "sha256:1mdh8npl8ma5ypafp6bzhjxim2if3ygny7nm0rb5689x40b1c83b";
      };
    };
    ppx_assert = 
    {
      pname = "ppx_assert";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_assert-v0.15.0.tar.gz";
        sha256 = "0rsr1yz2rs12w6qw0dz09dg3k2x2pfgd014fgp6nj993hhznapsf";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_here ppx_compare
        ppx_cold ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_assert/ppx_assert.v0.15.0";
        hash = "sha256:1ll9q69y6bj8s10qmkrmka10kd8zvkb50r1snaf2hfsldsn9qg31";
      };
    };
    ppx_base = 
    {
      pname = "ppx_base";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_base-v0.15.0.tar.gz";
        sha256 = "181w7y2has8jsrqdsvd08q5nhnkx523vwsk3lg0cjix55qssvfyn";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_hash ppx_enumerate
        ppx_compare ppx_cold ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_base/ppx_base.v0.15.0";
        hash = "sha256:0ilg603nkmn7mzvasyibhyalgw92w4lfgwpgwhwk7z50yrw3dqb7";
      };
    };
    ppx_cold = 
    {
      pname = "ppx_cold";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_cold-v0.15.0.tar.gz";
        sha256 = "13gqmfw2sq80anag9bwpm35600l1fnfn7mh9cbj1291k84rsx7wb";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_cold/ppx_cold.v0.15.0";
        hash = "sha256:1m38jiza7vdnkngw9nfz0rhk31yn206kycmnr87g6zx3mdp2k898";
      };
    };
    ppx_compare = 
    {
      pname = "ppx_compare";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_compare-v0.15.0.tar.gz";
        sha256 = "11bkw7fgzfay8ws0piwphqip3y2lk2c9s2gil3zisnbvka92h1va";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_compare/ppx_compare.v0.15.0";
        hash = "sha256:02y9vlqqqxq44lfwxq6as2wqqzilwqzky4dqykafbmn603mnv5y6";
      };
    };
    ppx_derivers = 
    {
      pname = "ppx_derivers";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
        hash = "sha256:1hj1ina0n7pgz16mrvijczapw75pd0hif0i18dpw7d1fyg2qr8py";
      };
    };
    ppx_deriving = 
    {
      pname = "ppx_deriving";
      version = "5.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_deriving/releases/download/v5.2.1/ppx_deriving-v5.2.1.tbz";
        sha256 = "11h75dsbv3rs03pl67hdd3lbim7wjzh257ij9c75fcknbfr5ysz9";
      };
      opamInputs = 
      {
        inherit (selection) result ppxlib ppx_derivers ocamlfind ocaml dune
        cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_deriving/ppx_deriving.5.2.1";
        hash = "sha256:0n4j9a5qh5fzxc68shhkhwqfajz49rjb8ryp9lx8ykl1zxddf89k";
      };
    };
    ppx_enumerate = 
    {
      pname = "ppx_enumerate";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_enumerate-v0.15.0.tar.gz";
        sha256 = "16yhk3xk2hskmlspb6mikmdp60qaypyiqgq9p17kxpial6fgpdfy";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_enumerate/ppx_enumerate.v0.15.0";
        hash = "sha256:1yp6h8n9177zp1gxai5s8rpqv9affjafp98svgawhnw66g96653j";
      };
    };
    ppx_hash = 
    {
      pname = "ppx_hash";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_hash-v0.15.0.tar.gz";
        sha256 = "048pim0xicj8j9whd5lnchf62788sk3w89h12aybbalk1xm6dfs5";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_compare ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_hash/ppx_hash.v0.15.0";
        hash = "sha256:18mhr158ky23cbriz2w4b5dj3xj55z9i2r5ifix9m8sq7zqqa6x7";
      };
    };
    ppx_here = 
    {
      pname = "ppx_here";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_here-v0.15.0.tar.gz";
        sha256 = "1pyaw31j9n6r98ar947n3j2qj6rrszbdxr8jghk96j4ajdy05g65";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_here/ppx_here.v0.15.0";
        hash = "sha256:12wgavjp9q0sbkymzzih9p4j80952dbh9djr0hpmx0by20dsr2in";
      };
    };
    ppx_inline_test = 
    {
      pname = "ppx_inline_test";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_inline_test-v0.15.0.tar.gz";
        sha256 = "06w7l575wqw2zgvsfdlslwxd6ni1nbw9jhimd7zy5a64md0x2y1z";
      };
      opamInputs = 
      {
        inherit (selection) time_now ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_inline_test/ppx_inline_test.v0.15.0";
        hash = "sha256:15vx091zg41k0himh9s5n6bh13l23sm4zrbpmp6j50ra5gd16bks";
      };
    };
    ppx_optcomp = 
    {
      pname = "ppx_optcomp";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_optcomp-v0.15.0.tar.gz";
        sha256 = "1vd6ra0f1cm1kiqdh0iyzh24bp0ndl3s2va5z0mrw3y8ngbp0kn4";
      };
      opamInputs = 
      {
        inherit (selection) stdio ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_optcomp/ppx_optcomp.v0.15.0";
        hash = "sha256:062wk4jw134j10nkmch4r5j18zizc4r2f0x1vdsbi9jzr9vzzl3n";
      };
    };
    ppx_sexp_conv = 
    {
      pname = "ppx_sexp_conv";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_sexp_conv/archive/refs/tags/v0.15.1.tar.gz";
        sha256 = "179f1iz504l008b3p3d9q2nj44wv7y31pc997x32m6aq1j2lfip3";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_conv/ppx_sexp_conv.v0.15.1";
        hash = "sha256:17303ra9w8cngiaz0s9q6d8617vyfx2nlz1kb813bs0g4vnj27mf";
      };
    };
    ppx_yojson_conv_lib = 
    {
      pname = "ppx_yojson_conv_lib";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/ppx_yojson_conv_lib-v0.15.0.tar.gz";
        sha256 = "115nlv3apiwsbay6188916zddpf84bnqdcbrygqw2vjnykpwblpr";
      };
      opamInputs = 
      {
        inherit (selection) yojson ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_yojson_conv_lib/ppx_yojson_conv_lib.v0.15.0";
        hash = "sha256:07pckbhr0nbswij1z61mw2qkanz1swp5rns7m04487rkphw2lwa2";
      };
    };
    ppxlib = 
    {
      pname = "ppxlib";
      version = "0.27.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppxlib/releases/download/0.27.0/ppxlib-0.27.0.tbz";
        sha256 = "0qlcnb2aas6h69zgjbygjhmw9gvna4iwa3hfh9rnmzbg3l99cjvn";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib0 ppx_derivers
        ocaml-compiler-libs ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppxlib/ppxlib.0.27.0";
        hash = "sha256:0xj93srv7brpwaydkslqgi1k7x79nybdp90h61hyjnsd3i7r3x1h";
      };
    };
    re = 
    {
      pname = "re";
      version = "1.10.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-re/releases/download/1.10.4/re-1.10.4.tbz";
        sha256 = "0z3lracww84cswj0a4s28x987sk28c7h2j87hb3iv6xa011kxsw3";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/re/re.1.10.4";
        hash = "sha256:00918wlxkkbj8dwpiwpyyvc8falk4ddrf0pxn5v2kahc2jl251vg";
      };
    };
    react = 
    {
      pname = "react";
      version = "1.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/react/releases/react-1.2.2.tbz";
        sha256 = "16cg4byj8lfbbw96dhh8sks5y9n1c3fshz7f2p8m7wgisqax7bf4";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/react/react.1.2.2";
        hash = "sha256:1airidp9cw8sk92jc3bvarph3pc43qaf3hcywi0anmpznsygcm0z";
      };
    };
    result = 
    {
      pname = "result";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
        sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/result/result.1.5";
        hash = "sha256:0ybmvlisfz5swvbcq855czz1ysv9zxmb79f1m0x8284hczmfm98f";
      };
    };
    seq = 
    {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/seq/seq.base";
        hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
      };
    };
    sexplib0 = 
    {
      pname = "sexplib0";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/sexplib0/archive/refs/tags/v0.15.1.tar.gz";
        sha256 = "1cv78931di97av82khqwmx5s51mrn9d2b82z0si88gxwndz83kg8";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib0/sexplib0.v0.15.1";
        hash = "sha256:1yg5rknfbx67wrs3gampx3jmcw9si38n90cj4kg5626k41nmhsc0";
      };
    };
    spawn = 
    {
      pname = "spawn";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/spawn/archive/v0.15.1.tar.gz";
        sha256 = "0l4xq43dxsvxli9kkpnywrw81dyn11bfpdlsd36kyv5b9wqyxzcs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/spawn/spawn.v0.15.1";
        hash = "sha256:18cl7lgcf5gl3r5ffdqiza5hydjgn8hwk4lsb6gsibv8jd7jx8bq";
      };
    };
    stdio = 
    {
      pname = "stdio";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/stdio-v0.15.0.tar.gz";
        sha256 = "0jsyg4jlp76d9gx1fngms6nfs7dcpsysdsvkywjq9a663n994wn3";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdio/stdio.v0.15.0";
        hash = "sha256:19z0wh8sm8ldwwpqq2hxn85b74z1g3jlkx7vfpqknm0pxhill7m1";
      };
    };
    stdlib-shims = 
    {
      pname = "stdlib-shims";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
        sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdlib-shims/stdlib-shims.0.3.0";
        hash = "sha256:1hwyzzcx7clz4p58fj3n6frq2srbxdmhmxxd6n6mpw9gj2vs6yiw";
      };
    };
    stdune = 
    {
      pname = "stdune";
      version = "3.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.2.0/chrome-trace-3.2.0.tbz";
        sha256 = "1g6m3a5b1nhvrxw5agzmng7ayy1rwbib56x8dyr1xvbrmvkbq7xx";
      };
      opamInputs = 
      {
        inherit (selection) pp ordering ocaml dyn dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdune/stdune.3.2.0";
        hash = "sha256:19yji4c393xijl59ky6h6ahi63cylwymavbkj33z10kp9hhdx0fa";
      };
    };
    time_now = 
    {
      pname = "time_now";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.15/files/time_now-v0.15.0.tar.gz";
        sha256 = "1a6b1f55mwci1bd8w8vji0qn6wbs60jbwixvwgy4klx2blq57cqk";
      };
      opamInputs = 
      {
        inherit (selection) ppx_optcomp ppx_base ocaml jst-config
        jane-street-headers dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/time_now/time_now.v0.15.0";
        hash = "sha256:1l6ffa9f0i1kpm2fgmhl2f63bbswd8sgzjbfgpcxkgxsivjgp6qf";
      };
    };
    topkg = 
    {
      pname = "topkg";
      version = "1.0.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/topkg/releases/topkg-1.0.5.tbz";
        sha256 = "1iyinmcfqpprk7k4cc51nqgypayprbj4larwcfqw86k5dri84825";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/topkg/topkg.1.0.5";
        hash = "sha256:04vg4zic7f6zk44vkvqw2fcr562hl7d0gklv3vgphk4n3bnqbcyy";
      };
    };
    trie = 
    {
      pname = "trie";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/trie/archive/1.0.0.tar.gz";
        sha256 = "1slq4kiwnc723dsaw15ms7xxpqz061v8zck1m6iyc5j2li70by62";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/trie/trie.1.0.0";
        hash = "sha256:1ds07ikjjymacnlxfx1widfi7qz0js61lsqqq0xa90501p17nq10";
      };
    };
    tyxml = 
    {
      pname = "tyxml";
      version = "4.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/tyxml/releases/download/4.5.0/tyxml-4.5.0.tbz";
        sha256 = "0s30f72m457c3gbdmdwbx7ls9zg806nvm83aiz9qkpglbppwr6n6";
      };
      opamInputs = 
      {
        inherit (selection) uutf seq re ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tyxml/tyxml.4.5.0";
        hash = "sha256:1lw91vsiijp4n6vgpfbws72c1v7a1b0v1fkxd7spasl8z27ljq2g";
      };
    };
    uchar = 
    {
      pname = "uchar";
      version = "0.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/uchar/releases/download/v0.0.2/uchar-0.0.2.tbz";
        sha256 = "1w2saw7zanf9m9ffvz2lvcxvlm118pws2x1wym526xmydhqpyfa7";
      };
      opamInputs = {
                     inherit (selection) ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uchar/uchar.0.0.2";
        hash = "sha256:028vff7rkmhyyn3xr5flfkc3ihz0axirbg538an8wbsmc4y1gv02";
      };
    };
    utop = 
    {
      pname = "utop";
      version = "2.10.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/utop/releases/download/2.10.0/utop-2.10.0.tbz";
        sha256 = "001dg31355861kbqfj91yxlcfv6723i3wrrjmh1ccqgaz6i1cpa7";
      };
      opamInputs = 
      {
        inherit (selection) zed react ocamlfind ocaml lwt_react lwt logs
        lambda-term dune cppo base-unix base-threads;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/utop/utop.2.10.0";
        hash = "sha256:1d4n00d3jb0f4njgsbhxq7czq9mpx9nkcgaln8zmrkjgfrlvprjs";
      };
    };
    uucp = 
    {
      pname = "uucp";
      version = "14.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uucp/releases/uucp-14.0.0.tbz";
        sha256 = "1yx9nih3d9prb9zizq8fzmmqylf24a6yifhf81h33znrj5xn1mpj";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        uutf = selection.uutf or null;
        uunf = selection.uunf or null;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uucp/uucp.14.0.0";
        hash = "sha256:03h0lnfnb4sad9lndnv8p5ylpwvp8gzqs9dk3v3cz9vz156fi99d";
      };
    };
    uuseg = 
    {
      pname = "uuseg";
      version = "14.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uuseg/releases/uuseg-14.0.0.tbz";
        sha256 = "1g9zyzjkhqxgbb9mh3cgaawscwdazv6y8kdqvmy6yhnimmfqv25p";
      };
      opamInputs = 
      {
        inherit (selection) uucp topkg ocamlfind ocamlbuild
        ocaml;
        uutf = selection.uutf or null;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uuseg/uuseg.14.0.0";
        hash = "sha256:0j96m881gh80g7sfy8va4l2w7gmijv7dznk38ndl33k6pyhdikna";
      };
    };
    uutf = 
    {
      pname = "uutf";
      version = "1.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uutf/releases/uutf-1.0.3.tbz";
        sha256 = "0s05r8ggp1g97zq4rnvbxzj22pv8ld0k5wsdw662jw0y7mhsawl7";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uutf/uutf.1.0.3";
        hash = "sha256:1x57h3bc68rsm2kd18wjbkfjk67shak6jgplp7paw97faqgmgx3x";
      };
    };
    xdg = 
    {
      pname = "xdg";
      version = "3.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.2.0/chrome-trace-3.2.0.tbz";
        sha256 = "1g6m3a5b1nhvrxw5agzmng7ayy1rwbib56x8dyr1xvbrmvkbq7xx";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/xdg/xdg.3.2.0";
        hash = "sha256:198zx7qyg0lj6b1cxspwpsdcg80m9zmmyfcq21qcizz8rdlc4v47";
      };
    };
    yojson = 
    {
      pname = "yojson";
      version = "2.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/yojson/releases/download/2.0.1/yojson-2.0.1.tbz";
        sha256 = "0dn8l220b4yv09rdg1xb8drjc1m4z3wifkrrb1m6b52a59rbrj4b";
      };
      opamInputs = 
      {
        inherit (selection) seq ocaml dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/yojson/yojson.2.0.1";
        hash = "sha256:1nsm2nd5vy6knzfll8q8q59b1rp029cd4l4j67znhb7gl37pj6ih";
      };
    };
    zed = 
    {
      pname = "zed";
      version = "3.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/zed/releases/download/3.2.0/zed-3.2.0.tbz";
        sha256 = "0gji5rp44mqsld117n8g93cqg8302py1piqshmvg63268fylj8rl";
      };
      opamInputs = 
      {
        inherit (selection) uutf uuseg uucp uchar result react ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/zed/zed.3.2.0";
        hash = "sha256:08kbibpismyxhymv2hr00q3xzcb3zmsxdgq1iz4iha2yd0p3whxb";
      };
    };
  };
}

